services:
  - type: web
    name: exoclassifier-frontend
    env: node
    plan: free
    buildCommand: rm -rf node_modules .next && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: /api
    healthCheckPath: /